name: CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  ssh-deploy:
    runs-on: [self-hosted, shopdesk]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      

      - name: SSH into server and run commands
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_IP: ${{ secrets.SSH_IP }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_IP" "
            if [ -d 'shopdesk-fe' ]; then
              cd shopdesk-fe &&
              # Kill any process running on port 7777
              echo 'Killing any process running on port 7777...' &&
              echo '$SSH_PASSWORD' | sudo -S fuser -k 7777/tcp || echo 'No process found on port 7777' &&
              echo 'Pulling latest changes...' &&
              git reset --hard HEAD &&  # Discard local changes
              git pull origin main
            else
              git clone $REPO_URL &&
              cd $(basename $REPO_URL .git)
            fi &&
            echo 'Installing dependencies...' &&
            bun install &&
            bun run build &&
            bun start
          "
            
